version: 2

references:

  ## Cache

  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Workspace

  workspace: &workspace
    ~/workspace
  attach_debug_workspace: &attach_debug_workspace
    attach_workspace:
      at: *workspace
  attach_release_workspace: &attach_release_workspace
    attach_workspace:
      at: *workspace
  persist_debug_workspace: &persist_debug_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - app/build/intermediates
        - app/build/outputs/androidTest-results
        - app/build/outputs/apk
        - app/build/outputs/code-coverage
        - app/build/test-results
  persist_release_workspace: &persist_release_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - app/build

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

## Keys

  # google-services.json
  decode_google_services_key: &decode_google_services_key
    run:
      name: Decode google services key
      command: echo GOOGLE_SERVICES_KEY > google-services.json


  # Google Play Service acc key
  decode_gplay_key: &decode_gplay_key
    run:
      name: Decode Google Play service acc key
      command: echo $GOOGLE_PLAY_KEY > google_play_key.json

  # Android signing key
  decode_keystore_file: &decode_keystore_file
    run:
      name: Decode keystore.properties
      command: echo $KEYSTORE | base64 -di > keystore.properties

jobs:

  ## Build debug APK and instrumented test APK
  build_debug:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - *decode_keystore_file
      - *decode_gplay_key
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - *save_cache
      - run:
          name: Gradle build (debug)
          command: ./gradlew -PciBuild=true :app:assembleDebug :app:assembleAndroidTest
      - *persist_debug_workspace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/

  ## Build release APK
  build_release:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - *decode_keystore_file
      - *decode_gplay_key
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - *save_cache
      - run:
          name: Gradle build (release)
          command: ./gradlew -PciBuild=true :app:assembleRelease
      - *persist_release_workspace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/
      - store_artifacts:
          path: app/build/outputs/mapping/
          destination: /mapping/

  ## Run unit tests
  test_unit:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - *save_cache
      - run:
          name: Run platform unit tests
          command: ./gradlew -PciBuild=true :app:testPlatformDebugUnitTest
      - run:
          name: Run servicesApi unit tests
          command: ./gradlew -PciBuild=true :app:testServicesApiDebugUnitTest
      - *persist_debug_workspace
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/
      - store_test_results:
          path: app/build/test-results/
          destination: /test-results/

  ## Run instrumented tests
  test_instrumented:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

  ## Deploy release APK to Google Play Alpha
  deploy:
    <<: *android_config
    steps:
      - checkout
      - *attach_release_workspace
      - *restore_cache
      - *decode_keystore_file
      - *decode_gplay_key
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Commenting
          command: echo 'Deploying'
      - run:
          name: Deploy to Google Play alpha
          command: ./gradlew publishPlatformRelease

workflows:
  version: 2
  workflow:
    jobs:
    - build_debug
    - build_release
    - test_unit:
        requires:
          - build_debug
    - test_instrumented:
        requires:
          - build_debug
    - deploy:
        filters:
          branches:
            only:
              - master
        requires:
          - build_release
          - test_unit
          - test_instrumented